-- ============================================================================
--  Distoner · Semilla de productos (23 referencias)
--  GENERADO automáticamente por scripts/generate-seed.mjs — no editar a mano.
--  Ejecutar en Supabase → SQL Editor DESPUÉS de schema.sql.
--  Es idempotente: se puede volver a correr; actualiza los existentes por id.
-- ============================================================================

insert into public.productos
  (id, inventory_number, name, reference, color, brand, category, description,
   price, stock, image, secondary_image, source_url, visible, sort_order)
values
  ('ic-951-cy', 1, 'Cartucho PrintKing H-951XL Cian', 'H-951XL CY', 'Cian', 'PrintKing', 'ink-cartridge', 'Cartucho de tinta compatible, alta capacidad XL. Referencia suministrada: H-951XL CY.', null, 1, '/images/products/cliente/h-951xl.jpeg', '/images/products/h951-cyan.jpg', 'https://www.1ink.com/hp-951xl-ink-cartridge-cyan-cn046an-remanufactured-replacement/', true, 1),
  ('ic-951-yl', 2, 'Cartucho PrintKing H-951XL Amarillo', 'H-951XL YL', 'Amarillo', 'PrintKing', 'ink-cartridge', 'Cartucho de tinta compatible, alta capacidad XL. Referencia suministrada: H-951XL YL.', null, 1, '/images/products/cliente/h-951xl.jpeg', '/images/products/h951-yellow.jpg', 'https://www.houseofinks.com/hp-951xl-cn048an-high-yield-yellow-ink-cartridge-remanufactured-shows-accurate-ink-levels/', true, 2),
  ('ic-951-mg', 3, 'Cartucho PrintKing H-951XL Magenta', 'H-951XL MG', 'Magenta', 'PrintKing', 'ink-cartridge', 'Cartucho de tinta compatible, alta capacidad XL. Referencia suministrada: H-951XL MG.', null, 1, '/images/products/cliente/h-951xl.jpeg', '/images/products/h951-magenta.jpg', 'https://www.1ink.com/hp-951xl-ink-cartridge-magenta-cn047an-remanufactured-replacement/', true, 3),
  ('ic-950-bk', 4, 'Cartucho PrintKing H-950XL Negro', 'H-950XL BK', 'Negro', 'PrintKing', 'ink-cartridge', 'Cartucho de tinta compatible, alta capacidad XL. Referencia suministrada: H-950XL BK.', null, 1, '/images/products/h950-black.jpg', null, 'https://www.swiftink.com/product/remanufactured-high-yield-black-pigment-based-ink-cartridge-for-cn045an-hp-950xl/', true, 4),
  ('tn-tk3162', 5, 'Tóner compatible TK-3162', 'TK-3162', 'Negro', 'Kyocera', 'toner', 'Tóner compatible negro. Referencia suministrada: TK-3162.', null, 1, '/images/products/cliente/tk-3162.jpeg', '/images/products/tk3162.jpg', 'https://www.inktechnologies.com/kyocera-mita-tk-3162-black-toner-cartridge-genuine-oem', true, 5),
  ('tn-w1330a', 6, 'Tóner compatible HP 330A', 'W1330A · 330A', 'Negro', 'HP', 'toner', 'Tóner compatible negro. W1330A corresponde a la denominación comercial HP 330A.', null, 1, '/images/products/cliente/w1330a.jpeg', '/images/products/fisico/w1330a.jpg', 'https://tonercompatibleperu.com/producto/toner-hp-330a-w1330a-compatible/', true, 6),
  ('ib-t504-yl', 7, 'Botella de tinta T504/T544 Amarillo', 'T504 / T544', 'Amarillo', 'Epson compatible', 'ink-bottle', 'Botella de tinta de recarga amarilla para la familia de referencias T504/T544.', null, 1, '/images/products/cliente/t504-t544.jpeg', '/images/products/t504-yellow.png', 'https://sskaizen.com/co/producto/botella-tinta-epson-t504-70ml-yellow/', true, 7),
  ('ib-t504-mg', 8, 'Botella de tinta T504/T544 Magenta', 'T504 / T544', 'Magenta', 'Epson compatible', 'ink-bottle', 'Botella de tinta de recarga magenta para la familia de referencias T504/T544.', null, 1, '/images/products/cliente/t504-t544.jpeg', '/images/products/t504-magenta.png', 'https://sskaizen.com/co/producto/botella-tinta-epson-t504-70ml-magenta/', true, 8),
  ('ib-t504-cy', 9, 'Botella de tinta T504/T544 Cian', 'T504 / T544', 'Cian', 'Epson compatible', 'ink-bottle', 'Botella de tinta de recarga cian para la familia de referencias T504/T544.', null, 1, '/images/products/cliente/t504-t544.jpeg', '/images/products/fisico/t504-cyan.jpg', 'https://recargasrafaela.com.ar/producto/global-botella-tinta-para-epson-t504-t544-cian-70ml/', true, 9),
  ('ib-t504-bk', 10, 'Botella Premium Refill Ink 504/544 Negro', '504 / 544 Premium Refill Ink', 'Negro', 'Premium Refill Ink', 'ink-bottle', 'Botella de tinta negra de recarga. Referencia suministrada: 504/544 Premium Refill Ink.', null, 1, '/images/products/cliente/t504-t544.jpeg', '/images/products/fisico/t504-black.jpg', 'https://sumisoft.com.co/producto/tinta-generica-epson-504-544-negro/', true, 10),
  ('tn-w1510a', 11, 'Tóner compatible HP 151A', 'W1510A · 151A', 'Negro', 'HP', 'toner', 'Tóner compatible negro. W1510A corresponde a la denominación comercial HP 151A.', null, 1, '/images/products/cliente/w1510a.jpeg', null, 'https://compudisa.com.pe/producto/toner-hp-w1510a-laserjet-pro-151a-negro/', true, 11),
  ('tn-ce505a-cf280a', 12, 'Tóner compatible CE505A / CF280A', 'CE505A / CF280A', 'Negro', 'HP compatible', 'toner', 'Tóner compatible negro. Referencias suministradas: CE505A y CF280A.', null, 1, '/images/products/cliente/ce505a-cf280a.jpeg', '/images/products/fisico/ce505a.jpg', 'https://pro-laser.com/en/p/1740-hp-05a-ce505a-cf280a-compatible-toner-black.html', true, 12),
  ('tn-ce255x', 13, 'Tóner compatible CE255X', 'CE255X · 55X', 'Negro', 'HP compatible', 'toner', 'Tóner compatible negro de alta capacidad. Referencia suministrada: CE255X.', null, 1, '/images/products/cliente/ce255x.jpeg', '/images/products/fisico/ce255x.jpg', 'https://compatiblesperu.com/producto/toner-hp-55x-ce255x/', true, 13),
  ('tn-c531-cyan', 14, 'Tóner compatible cian', 'CC531A / CE411A / CF381A', 'Cian', 'HP compatible', 'toner', 'Tóner compatible cian. Se muestran juntas las tres referencias entregadas por el cliente.', null, 1, '/images/products/cliente/cc531a-ce411a-cf381a.jpeg', '/images/products/cc531a-cyan.jpg', 'https://colombiatoner.com/producto/cartucho-de-toner-color-cian-hp-laserjet-cc531a-304a-ce411a-305a-cf381a-312a-generico/', true, 14),
  ('tn-c533-magenta', 15, 'Tóner compatible magenta', 'CC533A / CE413A / CF383A', 'Magenta', 'HP compatible', 'toner', 'Tóner compatible magenta. Se muestran juntas las tres referencias entregadas por el cliente.', null, 1, '/images/products/cc533a-magenta.jpg', null, 'https://controlprint.com.mx/product/cartucho-de-toner-compatible-cc533a-ce413a-cf383a-magenta/', true, 15),
  ('tn-c532-yellow', 16, 'Tóner compatible amarillo', 'CC532A / CE412A / CF382A', 'Amarillo', 'HP compatible', 'toner', 'Tóner compatible amarillo. Se muestran juntas las tres referencias entregadas por el cliente.', null, 1, '/images/products/cc532a-yellow.jpg', null, 'https://www.alebo.ro/cartus-hp-cc532a-ce412a-cf382a-crg718', true, 16),
  ('tn-c530-black', 17, 'Tóner compatible negro', 'CC530A / CE410A / CF380A', 'Negro', 'HP compatible', 'toner', 'Tóner compatible negro. Se muestran juntas las tres referencias entregadas por el cliente.', null, 1, '/images/products/cc530a-black.jpg', null, 'https://controlprint.com.mx/product/cartucho-de-toner-generico-cc530a-ce410a-cf380a-negro/', true, 17),
  ('tn-sp3710', 18, 'Tóner compatible Ricoh SP3710', 'SP3710', 'Negro', 'Ricoh', 'toner', 'Tóner compatible negro para la familia Ricoh SP3710. Referencia suministrada: SP3710.', null, 1, '/images/products/cliente/sp3710.jpeg', '/images/products/fisico/sp3710.png', 'https://gruposuministros.co/toner-ricoh/433-toner-sp3710-ricoh-negro-para-impresoras-ricoh-sp3710-m320f-2143657890.html', true, 18),
  ('tn-q2612a-universal', 19, 'Tóner compatible universal Q2612A', 'Q2612A / FX9 / FX10 / CAN103 / 703 / 104 / 704', 'Negro', 'HP / Canon compatible', 'toner', 'Tóner compatible universal negro para las referencias Q2612A, FX9, FX10, CAN103, 703, 104 y 704.', null, 1, '/images/products/cliente/q2612a-universal.jpeg', '/images/products/fisico/q2612a.jpg', 'https://pro-laser.com/en/p/1014-hp-12a-q2612a-103-303-703-fx9-fx10-104-compatible-toners-black.html', true, 19),
  ('tn-w1500a', 20, 'Tóner compatible HP 150A', 'W1500A · 150A', 'Negro', 'HP compatible', 'toner', 'Tóner compatible negro. W1500A corresponde a la denominación comercial HP 150A.', null, 1, '/images/products/cliente/w1500a.jpeg', null, 'https://compatiblesperu.com/producto/toner-hp-150a-w1500a/', true, 20),
  ('tn-w1105a', 21, 'Tóner compatible HP 105A', 'W1105A · 105A', 'Negro', 'HP compatible', 'toner', 'Tóner compatible negro. W1105A corresponde a la denominación comercial HP 105A.', null, 1, '/images/products/cliente/w1105a.jpeg', '/images/products/fisico/w1105a.jpg', 'https://compatiblesperu.com/producto/toner-compatible-hp-105a-w1105a/', true, 21),
  ('tn-m111l', 22, 'Tóner compatible Samsung MLT-D111L', 'MLT-D111L · 1.8K', 'Negro', 'Samsung', 'toner', 'Tóner compatible negro; rendimiento indicado por el inventario: 1.800 páginas.', null, 1, '/images/products/cliente/mlt-d111l.jpeg', '/images/products/fisico/mltd111l.jpg', 'https://tonercompatibleperu.com/producto/toner-compatible-samsung-mlt-d111l/', true, 22),
  ('tn-cb435a', 23, 'Tóner compatible universal HP', 'CB435A / CB436A / CE285A', 'Negro', 'HP compatible', 'toner', 'Tóner compatible negro. Referencias suministradas: CB435A, CB436A y CE285A.', null, 1, '/images/products/cliente/cb435-cb436-ce285a.jpeg', '/images/products/fisico/cb435a.jpg', 'https://todocomputadoras.com.do/product/toner-cb435a-cb436a-ce285a-premium/', true, 23)
on conflict (id) do update set
  inventory_number = excluded.inventory_number,
  name             = excluded.name,
  reference        = excluded.reference,
  color            = excluded.color,
  brand            = excluded.brand,
  category         = excluded.category,
  description      = excluded.description,
  price            = excluded.price,
  stock            = excluded.stock,
  image            = excluded.image,
  secondary_image  = excluded.secondary_image,
  source_url       = excluded.source_url,
  sort_order       = excluded.sort_order;
